### ISSUE TITLE
Error: Your PHP version is not compiled with zip support

### ISSUE THREAD

**Issue by chaimawetcha** [Chumper/Zipper#118]
my php version is "Version de PHP : 7.1.9" and i am working in ubuntu and i have this problem

**Comment by mrsamirmh** [comment]
Same issue too. in php 7.1.12

**Comment by priyeshwar-AGL** [comment]
my php version is " PHP : 7.2." and i am working in ubuntu and i have this problem

**Comment by mrsamirmh** [comment]
Fixed after enabling zip extension in php.ini

**Comment by priyeshwar-AGL** [comment]
its enable but still not working 
[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

**Comment by mrsamirmh** [comment]
If you use different versions of php you can get specific modules for version of php with: 
php7.2 -m
or 
php7.1 -m. 

Maybe you are watching modules for php version which don't used in current project.

**Comment by priyeshwar-AGL** [comment]
I have php7.2  but still not working 

[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

**Comment by Ivan1234** [comment]
This helped me on AWS `sudo apt-get install php7.0-zip`
